# $$Feature-Engineering$$

- to use your domain knowledge to transform data into features that make ML algorithms work better
- 
- we used the breast cancer --- which feature is important
    - can come up with new features that would be relevant to the problem

- feature engineering - 
    - handling missing value 
    - Encoding ---> taking categorical feature -> into numeric columns
    - Scaling - we transform the column into a differnt scale
        - e.g age vs salary
        - age is in 10s and salary in 100 thousands
        - if we don't scale, then salary will be the important feature for a ML algo
        - ML algorithms will be biased towards salary always
        - so we use scaling to make sure each feature is given equal importance
    - Creating new features --- based on existing data --- e.g ratios, or differences, or aggregation
- 
1. Feature Transformation
    - feature encoding/scaling
2. Feature Creation
3. Feature Selection
4. Feature Extraction

https://www.datacamp.com/tutorial/feature-engineering

### Categorical vs Numeric

In [102]:
import pandas as pd
import seaborn as sns
import numpy as np

df_penguins = sns.load_dataset("penguins")
df_penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

- look at features, find categorical ---> numeric
- find difference is scale ---> scaling/normalization/standardization of dataset

In [103]:
df_penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

- wherever you see `str` or `object`
    - convert these to numerical
    - ONLY THEN, will our ML model be able to use them
-  
-

#### Label Encoding
- Idea: 
    - Adelie -> 0
    - Chinstrap -> 1
    - Gentoo -> 2
- 
-

In [104]:
# first way --- Manual conversion using map()

species = {
    'Adelie': 0,
    'Chinstrap': 1,
    'Gentoo': 2
}

df_penguins['species_le'] = df_penguins['species'].map(species)

df_penguins['sex_le'] = df_penguins["sex"].map({'Male': 0, 'Female': 1})

In [105]:
df_penguins.island.unique()

<StringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [106]:
# categorical columns can be encoded quickly
df_penguins['sex_cat'] = df_penguins['sex'].astype('category')
df_penguins['sex_cat_le'] = df_penguins['sex_cat'].cat.codes
df_penguins.sample(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_le,sex_le,sex_cat,sex_cat_le
96,Adelie,Dream,38.1,18.6,190.0,3700.0,Female,0,1.0,Female,0
234,Gentoo,Biscoe,45.8,14.6,210.0,4200.0,Female,2,1.0,Female,0
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male,2,0.0,Male,1
330,Gentoo,Biscoe,50.5,15.2,216.0,5000.0,Female,2,1.0,Female,0
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,Male,2,0.0,Male,1

In [107]:
# Third method --- Sklearn --->
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df_penguins['species_LE'] = encoder.fit_transform(df_penguins['species'])
df_penguins['sex_LE'] = encoder.fit_transform(df_penguins['sex'])

df_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_le,sex_le,sex_cat,sex_cat_le,species_LE,sex_LE
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0.0,Male,1,0,1
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,1.0,Female,0,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,1.0,Female,0,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-1,0,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,1.0,Female,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,-1,2,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,1.0,Female,0,2,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,0.0,Male,1,2,1
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,1.0,Female,0,2,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,0.0,Male,1,2,1

#### One Hot Encoding

Idea:

- Create one new column per category.
- Use 0/1 to indicate presence.

Example for `species`:

Original:

| species   |
|----------|
| Adelie   |
| Gentoo   |
| Chinstrap|

After one-hot:

| species_Adelie | species_Gentoo | species_Chinstrap |
|----------------|----------------|-------------------|
| 1              | 0              | 0                 |
| 0              | 1              | 0                 |
| 0              | 0              | 1                 |

No fake ordering between categories.

We can do this easily with `pandas.get_dummies`.

In [108]:
# Get_dummies

encoded_df = pd.get_dummies(df_penguins, columns = ['island','sex'] )
encoded_df

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_le,sex_le,sex_cat,sex_cat_le,species_LE,sex_LE,island_Biscoe,island_Dream,island_Torgersen,sex_Female,sex_Male
0,Adelie,39.1,18.7,181.0,3750.0,0,0.0,Male,1,0,1,False,False,True,False,True
1,Adelie,39.5,17.4,186.0,3800.0,0,1.0,Female,0,0,0,False,False,True,True,False
2,Adelie,40.3,18.0,195.0,3250.0,0,1.0,Female,0,0,0,False,False,True,True,False
3,Adelie,NaN,NaN,NaN,NaN,0,NaN,NaN,-1,0,2,False,False,True,False,False
4,Adelie,36.7,19.3,193.0,3450.0,0,1.0,Female,0,0,0,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,NaN,NaN,NaN,NaN,2,NaN,NaN,-1,2,2,True,False,False,False,False
340,Gentoo,46.8,14.3,215.0,4850.0,2,1.0,Female,0,2,0,True,False,False,True,False
341,Gentoo,50.4,15.7,222.0,5750.0,2,0.0,Male,1,2,1,True,False,False,False,True
342,Gentoo,45.2,14.8,212.0,5200.0,2,1.0,Female,0,2,0,True,False,False,True,False
343,Gentoo,49.9,16.1,213.0,5400.0,2,0.0,Male,1,2,1,True,False,False,False,True

In [109]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output= False)

df_penguins.dropna(inplace=True)

ohedata = ohe.fit_transform(df_penguins[['sex']])
# print(ohedata)

##### Exercise:

- Label Encode using map() for `sex` and `island`

- Implement get dummies to do OHE of the data columns
- implement ohe on `species` and `sex`
- take the ohe output of `species` and `sex`, and add it to the dataframe as separate columns

In [110]:
df_onehot = pd.DataFrame(ohedata ,columns = ohe.get_feature_names_out())
df_onehot

     sex_Female  sex_Male
0           0.0       1.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           0.0       1.0
..          ...       ...
328         1.0       0.0
329         1.0       0.0
330         0.0       1.0
331         1.0       0.0
332         0.0       1.0

[333 rows x 2 columns]

In [111]:
df_penguins = pd.concat([df_penguins, df_onehot], axis = 1 )
df_penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_le,sex_le,sex_cat,sex_cat_le,species_LE,sex_LE,sex_Female,sex_Male
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0.0,0.0,Male,1.0,0.0,1.0,0.0,1.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0.0,1.0,Female,0.0,0.0,0.0,1.0,0.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0.0,1.0,Female,0.0,0.0,0.0,1.0,0.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0.0,1.0,Female,0.0,0.0,0.0,0.0,1.0
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,0.0,0.0,Male,1.0,0.0,1.0,1.0,0.0

In [120]:
df_data = pd.DataFrame({
    'Experience': [1, 5, 6, 9, 10],
    'Salary':[100_000, 500_000, 600_000, 900_000, 1_000_000 ]
})
df_data['Salary_100k'] = (df_data.Salary /100_000).astype('int16')
df_data

   Experience   Salary  Salary_100k
0           1   100000            1
1           5   500000            5
2           6   600000            6
3           9   900000            9
4          10  1000000           10

### Feature Scaling
- `Standardization` rescales a data to have a `mean of 0` and a `standard deviation of 1`
    - 
-

In [127]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

data = scaler.fit_transform(df_data)
print(data.round(2))
pd.DataFrame(data.round(2)).describe()

[[-1.63 -1.63 -1.63]
 [-0.38 -0.38 -0.38]
 [-0.06 -0.06 -0.06]
 [ 0.88  0.88  0.88]
 [ 1.19  1.19  1.19]]

             0        1        2
count  5.00000  5.00000  5.00000
mean   0.00000  0.00000  0.00000
std    1.11752  1.11752  1.11752
min   -1.63000 -1.63000 -1.63000
25%   -0.38000 -0.38000 -0.38000
50%   -0.06000 -0.06000 -0.06000
75%    0.88000  0.88000  0.88000
max    1.19000  1.19000  1.19000

- both these columns contained the same information
    - the pattern is!!
    - ML algorithms need patterns, not exactly just data
    - 
-

https://www.youtube.com/watch?v=sxEqtjLC0aM

- `Normalization` - rescales a dataset so that each value falls `between 0 and 1`
    - implement using the minmax scaling
    - 

-

In [129]:
from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()

data = scaler_minmax.fit_transform(df_data)
print(data.round(2))

pd.DataFrame(data.round(2)).describe()

[[0.   0.   0.  ]
 [0.44 0.44 0.44]
 [0.56 0.56 0.56]
 [0.89 0.89 0.89]
 [1.   1.   1.  ]]

             0        1        2
count  5.00000  5.00000  5.00000
mean   0.57800  0.57800  0.57800
std    0.39651  0.39651  0.39651
min    0.00000  0.00000  0.00000
25%    0.44000  0.44000  0.44000
50%    0.56000  0.56000  0.56000
75%    0.89000  0.89000  0.89000
max    1.00000  1.00000  1.00000

In [112]:
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# let's bring iris from seaborn
df_pen = sns.load_dataset('penguins')

# assuming data is clean and balanced

# choose a model
model = DecisionTreeClassifier(max_depth= 3, criterion= 'gini')

# train test split
X = df_pen.drop(['species','sex','island'], axis = 1) # Input Features
y = df_pen.species # Output feature

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify= y)

In [113]:
# fitting the model with data
model.fit(X_train, y_train) # train set goes to model

# Create some predictions --- on the testing 
y_predictions = model.predict(X_test)
y_predictions

# check model performance
# accuracy = accuracy_score(y_test, y_predictions)
# print(f"Decision Tree Model Accuracy: {accuracy*100:.2f}%")

array(['Adelie', 'Adelie', 'Gentoo', 'Gentoo', 'Chinstrap', 'Adelie',
       'Chinstrap', 'Gentoo', 'Chinstrap', 'Chinstrap', 'Adelie',
       'Gentoo', 'Chinstrap', 'Gentoo', 'Gentoo', 'Gentoo', 'Adelie',
       'Adelie', 'Gentoo', 'Gentoo', 'Chinstrap', 'Gentoo', 'Gentoo',
       'Adelie', 'Adelie', 'Adelie', 'Gentoo', 'Adelie', 'Gentoo',
       'Gentoo', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Gentoo', 'Gentoo', 'Adelie', 'Adelie', 'Gentoo', 'Chinstrap',
       'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Gentoo', 'Gentoo', 'Adelie', 'Adelie', 'Chinstrap',
       'Adelie', 'Gentoo', 'Chinstrap', 'Adelie', 'Chinstrap', 'Adelie',
       'Gentoo', 'Gentoo', 'Chinstrap', 'Gentoo', 'Gentoo', 'Chinstrap',
       'Gentoo', 'Adelie', 'Adelie', 'Gentoo'], dtype=object)